/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculatrice.h"

void *allumer_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	for (int i = 0; i < 6; ++i)
	{
		registre[i]=0;
	}
	globale=0;
	return (void *) &result;
}

long *ajouter_1_svc(calc *argp, struct svc_req *rqstp)
{
	static long  result;
	result=(argp->val2)+(argp->val1);
	return &result;
}

long *soustraire_1_svc(calc *argp, struct svc_req *rqstp)
{
	static long  result;

	result=(argp->val2)-(argp->val1);
	return &result;
}

long *multiplier_1_svc(calc *argp, struct svc_req *rqstp)
{
	static long  result;
	result=(argp->val2)*(argp->val1);
	return &result;
}

void *memoriser_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	registre[*argp]=globale;
}

long *extraire_1_svc(int *argp, struct svc_req *rqstp)
{
	static long  result;

	result=registre[*argp];
	return &result;
}

void *eteindre_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	for (int i = 0; i < 6; ++i)
	{
		registre[i]=0;
	}
	globale=0;

	return (void *) &result;
}
