/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculatrice.h"

bool_t
xdr_calc (XDR *xdrs, calc *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->val1))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->val2))
		 return FALSE;
	return TRUE;
}
