/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculatrice.h"
static int try=-1;
int menu();

void calcule(int choice)
{
	void  *result_1;
	char *allumer_1_arg;
	long  *result_2;
	calc  ajouter_1_arg;
	long  *result_3;
	calc  soustraire_1_arg;
	long  *result_4;
	calc  multiplier_1_arg;
	void  *result_5;
	int  memoriser_1_arg=-1;
	long  *result_6;
	int  extraire_1_arg;
	void  *result_7;
	char *eteindre_1_arg;
	int reg;
	printf("=============================================\n");
	switch(choice)
	{
		case 1:
				printf("ALLUMAGE\n");
				allumer();
				break;
		case 2:
				printf("ADDITION\n");
				printf("Entrez la valeur a ajouter \n");
				scanf("%ld",&(ajouter_1_arg.val2));
				ajouter_1_arg.val1=globale;
				result_2 = ajouter(&ajouter_1_arg);
				globale=(*result_2);
				break;
		case 3:
				printf("SOUSTRACTION\n");
				printf("Entrez la valeur a soustraire \n");
				scanf("%ld",&(soustraire_1_arg.val2));
				soustraire_1_arg.val1=globale;
				result_3 = soustraire(&soustraire_1_arg);
				globale=(*result_3);
				break;
		case 4:
				printf("MULTIPLICATION\n");
				printf("Entrez la valeur a multiplier \n");
				scanf("%ld",&(multiplier_1_arg.val2));
				multiplier_1_arg.val1=globale;
				result_4 = multiplier(&multiplier_1_arg);
				globale=(*result_4);
				break;
		case 5:
				printf("MEMORISATION\n");
				printf("La calculatrice contient 6 registres numerotés de 0 à 5\n");
				do
				{
					printf("Entrez le numero du registre \n");
					scanf("%d",&memoriser_1_arg);
				} while (memoriser_1_arg<0 || memoriser_1_arg>5);
				memoriser(&memoriser_1_arg);
				break;
		case 6:
				printf("EXTRACTION\n");
				printf("La calculatrice contient 6 registres numerotés de 0 à 5\n");
				do
				{
					printf("Entrez le numero du registre \n");
					scanf("%d",&extraire_1_arg);
				} while (extraire_1_arg<0 || extraire_1_arg>5);
				result_6 = extraire(&extraire_1_arg);
				globale=(*result_6);
				break;
		case 7:
				printf("EXTINCTION\n");
				eteindre();
				break;
		default:
				break;
	}
	printf("=============================================\n");
}


int main (int argc, char *argv[])
{
	char *host;
	int step=0;
	
	printf("---------------------------------------------\n");
	printf("Bienvenue dans calculatrice\n\n");
	int minitry=0;
	//printf("Premier\n");
	do
	{
		minitry=menu();
		if(minitry==7)
		{
			printf("AU REVOIR \n");
			printf("---------------------------------------------\n");
			return 0;
		}
	} while (minitry!=1);
	calcule (minitry);
	minitry=0;
	step=1;
	int mychoice;
	printf("CALCULATRICE ALLUMEE\n");
	do
	{
		mychoice=menu();
		if (mychoice==1)
		{
			printf("LA CALCULATRICE EST DEJA ALLUMEE\n");
		}
		else
		{
			if(step=1 && (mychoice == 2 || mychoice == 3|| mychoice == 4 ) )
			{
				int minichoice=3;
				do
				{
					printf("\t 1->ENTREZ UN SEUL  NOMBRE POUR LE CALCUL\n");
					printf("\t 2->ENTREZ DEUX NOMBRES POUR LE CALCUL\n");
					printf("\tDANS LE CAS 2, LA VALEUR GLOBALE EST ECRASEE\n");
					scanf("%d",&minichoice);
					printf("mon minichoice:%d\n",minichoice );
					//if (minichoice!= 1 && minichoice!= 2)
					//{
					//	printf("off\n");
					//}
					//else
						//printf("on\n");
				} while (minichoice!= 1 && minichoice!= 2);

				if (minichoice==2)
				{
					printf("Entrez le premier nombre \n");
					scanf("%ld",&globale);
				}
			}
			calcule (mychoice);
			printf("valeur de globale: %ld\n",globale );
		}
		
		
	} while (mychoice!=7);


	
exit (0);
}

/*------------------------------------*/
int menu()
{
	
	int valeur=0;
	printf("\t 1->ALLUMER LA CALCULATRICE\n");
	printf("\t 2->AJOUTER UN NOMBRE \n");
	printf("\t 3->SOUSTRAIRE UN NOMBRE\n");
	printf("\t 4->MULTIPLIER UN NOMBRE\n");
	printf("\t 5->MEMORISER VOTRE RESULTAT\n");
	printf("\t 6->EXTRAIT UNE VALEUR\n");
	printf("\t 7->QUITTER LA CALCULATRICE\n");
	do
	{
		printf("Entrez votre choix ...\n");
		scanf("%d",&valeur);
		try ++;		
		if (try==0 && valeur!=1 && valeur!=7)
		{
			printf("Vous devez allumer la calculatrice\n");
			try=-1;
		}
		
	} while (valeur <1 || valeur>7);
	
	return valeur;
}