/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculatrice.h"
void allumer()
{

	for (int i = 0; i < 6; ++i)
	{
		registre[i]=0;
	}
	globale=0;
}

long *ajouter(calc *argp)
{
	static long  result;
	result=(argp->val2)+(argp->val1);
	return &result;
}

long *soustraire(calc *argp)
{
	static long  result;

	result=(argp->val2)-(argp->val1);
	return &result;
}

long *multiplier(calc *argp)
{
	static long  result;
	result=(argp->val2)*(argp->val1);
	return &result;
}

void memoriser(int *argp)
{
	static char * result;
	registre[*argp]=globale;
}

long *extraire(int *argp)
{
	static long  result;

	result=registre[*argp];
	return &result;
}

void eteindre()
{

	for (int i = 0; i < 6; ++i)
	{
		registre[i]=0;
	}
	globale=0;

}
